[package]
name = "step_1_4"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
combu = "1.1.23"
argyle = "0.6.8"
climb = "2.0.5"
clishe = "0.2.8"
sarge = "3.0.0"


[[bin]]
name = "argyle_parser"
