[package]
name = "step_1_2"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
pin-project = "1.1.0"
futures = "0.3.28"

[dependencies.tokio]
version = "1.29.1"
features = ["macros", "rt", "time"]