[package]
name = "step_3_9"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
clap = {version="4.3.23", features=["derive", "env"]}
serde = "1.0.8"
toml = { version = "0.7", optional = true }
config = "0.13.3"