name: Cache tools

on:
  push:
    branches:
      # GitHub cache is scoped to the branch + default branch,
      # This is not a problem for tasks, because those are usually done in one branch
      # We need to cache tools we use on push to the default branch
      # Otherwise, it CI takes too long to run
      # See https://github.com/orgs/community/discussions/27059#discussioncomment-3254477
      - master
      - main

jobs:
  cache_tools:
    if: ${{ github.repository_owner != 'instrumentisto' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: ./.github/actions/install-student-ci-deps

